# Generated by Django 4.2.2 on 2023-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField(blank=True)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imdb', models.FloatField(blank=True)),
                ('genre', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True)),
                ('actor', models.ManyToManyField(to='film.actor')),
            ],
        ),
    ]
