# Generated by Django 4.2.2 on 2023-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('famale', 'famale')], max_length=10),
        ),
    ]
